# This playbook assumes that cyverse-ez-docker directory is located in /opt/cyverse-ez-docker/
# EJS Note 2/12/2019: ansible-galaxy fails ssl cert verify for galaxy.ansible.com/api. Can revert when fixed later

- name: this playbook will setup ez locally
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: include variables found in /etc/cyverse/ez.yml, if it exists; if error, just ignore
      include_vars:
        file: /etc/cyverse/ez.yml
      ignore_errors: yes

    - name: remove the ez role if update is forced
      command: ansible-galaxy remove docker
      when: ez_force_update is defined and ez_force_update == true

    - name: remove the ez role if update is forced
      command: ansible-galaxy remove portainer
      when: ez_force_update is defined and ez_force_update == true

    # note, ignoring errors since ansible-galaxy considers an existing role as an error
    - name: pull in any Ansible Galaxy roles from the requirements.yml
      command: "ansible-galaxy install -c -i -r {{ playbook_dir }}/requirements.yml"

    - name: including cyverse ez role
      include_role:
        name: docker

    - name: include portainer role
      include_role:
        name: portainer
      when: ansible_portainer_enabled is defined and ansible_portainer_enabled == true
